export const BRAND = {
  primary: '#1a365d',
  secondary: '#2b6cb0',
  accent: '#3182ce',
  success: '#276749',
  danger: '#c53030',
  warning: '#d69e2e',
  muted: '#718096',
  light: '#f7fafc',
  border: '#cbd5e0',
  darkBorder: '#a0aec0',
  white: '#ffffff',
  black: '#1a202c',
  tableHeaderBg: '#1a365d',
  tableHeaderText: '#ffffff',
  tableAltRow: '#edf2f7',
  tableBorder: '#cbd5e0',
  summaryBg: '#f7fafc',
  summaryBorder: '#cbd5e0',
  sectionHeaderBg: '#1a365d',
  sectionHeaderText: '#ffffff',
  panelBg: '#f0f7ff',
  panelBorder: '#bee3f8',
  panelHeaderBg: '#1a365d',
  panelHeaderText: '#ffffff',
  lightBlue: '#ebf8ff',
  mediumBlue: '#bee3f8',
  darkBlue: '#1a365d',
  grandTotalBg: '#1a365d',
  grandTotalText: '#ffffff',
} as const;

export const FONTS = {
  regular: 'Calibri',
  bold: 'Calibri-Bold',
  italic: 'Calibri-Italic',
  boldItalic: 'Calibri-BoldItalic',
} as const;

export const PAGE = {
  width: 595.28,
  height: 841.89,
  margin: { top: 40, bottom: 50, left: 40, right: 40 },
  contentWidth: 595.28 - 40 - 40,
} as const;
