/**
 * Shared system configuration for a fresh installation.
 * Used by seed-system / seed-reset-system and registration bootstrap.
 * No demo CRM rows — pipelines, event rules, and role permission defaults only.
 */
export const SYSTEM_ROLE_DEFS = [
  { name: 'Owner', permissions: ['*'] as string[] },
  {
    name: 'Admin',
    permissions: [
      'lead:list',
      'lead:read',
      'lead:create',
      'lead:update',
      'lead:delete',
      'lead:restore',
      'customer:list',
      'customer:read',
      'customer:create',
      'customer:update',
      'customer:delete',
      'customer:restore',
      'project:list',
      'project:read',
      'project:create',
      'project:update',
      'project:delete',
      'project:restore',
      'user:list',
      'user:read',
      'user:create',
      'user:update',
      'role:list',
      'role:read',
      'organization:read',
      'organization:update',
      'tracking:read',
      'tracking:update',
    ],
  },
  {
    name: 'Employee',
    permissions: [
      'lead:list',
      'lead:read',
      'lead:create',
      'lead:update',
      'customer:list',
      'customer:read',
      'customer:create',
      'customer:update',
      'project:list',
      'project:read',
      'project:update',
      'tracking:read',
      'tracking:update',
    ],
  },
] as const;

export const LEAD_PIPELINE = [
  {
    status: 'New',
    label: 'New',
    order: 1,
    isInitial: true,
    isFinal: false,
    allowedTransitions: ['Contacted', 'Rejected'],
    color: '#6b7280',
  },
  {
    status: 'Contacted',
    label: 'Contacted',
    order: 2,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['DesignPending', 'Rejected', 'Converted'],
    color: '#3b82f6',
  },
  {
    status: 'DesignPending',
    label: 'Design Pending',
    order: 3,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['BOQPending', 'Rejected'],
    color: '#8b5cf6',
  },
  {
    status: 'BOQPending',
    label: 'BOQ Pending',
    order: 4,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['EstimateSent', 'Rejected'],
    color: '#f59e0b',
  },
  {
    status: 'EstimateSent',
    label: 'Estimate Sent',
    order: 5,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['ProposalSent', 'Negotiation', 'Rejected'],
    color: '#10b981',
  },
  {
    status: 'ProposalSent',
    label: 'Proposal Sent',
    order: 6,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['Negotiation', 'Approved', 'Rejected'],
    color: '#06b6d4',
  },
  {
    status: 'Negotiation',
    label: 'Negotiation',
    order: 7,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['Approved', 'Rejected'],
    color: '#f97316',
  },
  {
    status: 'Approved',
    label: 'Approved',
    order: 8,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['Converted', 'Rejected'],
    color: '#22c55e',
  },
  {
    status: 'Rejected',
    label: 'Rejected',
    order: 9,
    isInitial: false,
    isFinal: true,
    allowedTransitions: [] as string[],
    color: '#ef4444',
  },
  {
    status: 'Converted',
    label: 'Converted',
    order: 10,
    isInitial: false,
    isFinal: true,
    allowedTransitions: [] as string[],
    color: '#14b8a6',
  },
];

export const CUSTOMER_PIPELINE = [
  {
    status: 'Active',
    label: 'Active',
    order: 1,
    isInitial: true,
    isFinal: false,
    allowedTransitions: ['Inactive', 'Archived'],
    color: '#22c55e',
  },
  {
    status: 'Inactive',
    label: 'Inactive',
    order: 2,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['Active', 'Archived'],
    color: '#f59e0b',
  },
  {
    status: 'Archived',
    label: 'Archived',
    order: 3,
    isInitial: false,
    isFinal: true,
    allowedTransitions: [] as string[],
    color: '#6b7280',
  },
];

export const PROJECT_PIPELINE = [
  {
    status: 'New',
    label: 'New',
    order: 1,
    isInitial: true,
    isFinal: false,
    allowedTransitions: ['DesignInProgress', 'OnHold', 'Cancelled'],
    color: '#6b7280',
  },
  {
    status: 'DesignInProgress',
    label: 'Design In Progress',
    order: 2,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['DesignApproved', 'OnHold', 'Cancelled'],
    color: '#3b82f6',
  },
  {
    status: 'DesignApproved',
    label: 'Design Approved',
    order: 3,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['Fabrication', 'OnHold', 'Cancelled'],
    color: '#8b5cf6',
  },
  {
    status: 'Fabrication',
    label: 'Fabrication',
    order: 4,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['DispatchReady', 'OnHold', 'Cancelled'],
    color: '#f59e0b',
  },
  {
    status: 'DispatchReady',
    label: 'Dispatch Ready',
    order: 5,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['Dispatched', 'OnHold'],
    color: '#f97316',
  },
  {
    status: 'Dispatched',
    label: 'Dispatched',
    order: 6,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['Installation', 'Cancelled'],
    color: '#10b981',
  },
  {
    status: 'Installation',
    label: 'Installation',
    order: 7,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['Completed', 'OnHold', 'Cancelled'],
    color: '#14b8a6',
  },
  {
    status: 'Completed',
    label: 'Completed',
    order: 8,
    isInitial: false,
    isFinal: true,
    allowedTransitions: [] as string[],
    color: '#22c55e',
  },
  {
    status: 'OnHold',
    label: 'On Hold',
    order: 9,
    isInitial: false,
    isFinal: false,
    allowedTransitions: ['DesignInProgress', 'Fabrication', 'Installation', 'Cancelled'],
    color: '#f59e0b',
  },
  {
    status: 'Cancelled',
    label: 'Cancelled',
    order: 10,
    isInitial: false,
    isFinal: true,
    allowedTransitions: [] as string[],
    color: '#ef4444',
  },
];

/** Event rules MUST use statuses from pipelines above — single source of truth */
export const EVENT_RULES: Record<
  string,
  Array<{ eventType: string; fromStatus: string | null; toStatus: string }>
> = {
  lead: [
    { eventType: 'created', fromStatus: null, toStatus: 'New' },
    { eventType: 'contacted', fromStatus: 'New', toStatus: 'Contacted' },
    { eventType: 'design.started', fromStatus: 'Contacted', toStatus: 'DesignPending' },
    { eventType: 'boq.started', fromStatus: 'DesignPending', toStatus: 'BOQPending' },
    { eventType: 'estimate.sent', fromStatus: 'BOQPending', toStatus: 'EstimateSent' },
    { eventType: 'proposal.sent', fromStatus: 'EstimateSent', toStatus: 'ProposalSent' },
    { eventType: 'negotiation.started', fromStatus: 'ProposalSent', toStatus: 'Negotiation' },
    { eventType: 'approved', fromStatus: 'Negotiation', toStatus: 'Approved' },
    { eventType: 'converted', fromStatus: 'Approved', toStatus: 'Converted' },
    { eventType: 'rejected', fromStatus: null, toStatus: 'Rejected' },
  ],
  customer: [
    { eventType: 'created', fromStatus: null, toStatus: 'Active' },
    { eventType: 'deactivated', fromStatus: 'Active', toStatus: 'Inactive' },
    { eventType: 'reactivated', fromStatus: 'Inactive', toStatus: 'Active' },
    { eventType: 'archived', fromStatus: null, toStatus: 'Archived' },
  ],
  project: [
    { eventType: 'created', fromStatus: null, toStatus: 'New' },
    { eventType: 'design.started', fromStatus: 'New', toStatus: 'DesignInProgress' },
    { eventType: 'design.approved', fromStatus: 'DesignInProgress', toStatus: 'DesignApproved' },
    { eventType: 'fabrication.started', fromStatus: 'DesignApproved', toStatus: 'Fabrication' },
    { eventType: 'fabrication.completed', fromStatus: 'Fabrication', toStatus: 'DispatchReady' },
    { eventType: 'dispatched', fromStatus: 'DispatchReady', toStatus: 'Dispatched' },
    { eventType: 'installation.started', fromStatus: 'Dispatched', toStatus: 'Installation' },
    { eventType: 'installation.completed', fromStatus: 'Installation', toStatus: 'Completed' },
    { eventType: 'put-on-hold', fromStatus: null, toStatus: 'OnHold' },
    { eventType: 'cancelled', fromStatus: null, toStatus: 'Cancelled' },
  ],
};
